# Triggering build
pipeline:
  build:
    image: docker
    commands:
      - apk add py-pip --no-cache
      - pip install docker-compose
      - apk add socat --no-cache
      - docker build -t cjchand/logstash-agent .
      - docker-compose down
      - docker-compose up -d
      - sleep 600
      - docker ps -a
      - curl 192.241.247.133:9200
      - echo "waffles" | socat - udp-sendto:192.241.247.133:5514
      - sleep 5
      - curl '192.241.247.133:9200/_all/_search?q=waffles' | grep waffles
      - docker-compose down
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  publish:
    image: cjchand/logstash-agent
    repo: cjchand/logstash-agent
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
