pipeline:
  build:
    image: docker
    commands:
      - apk add py-pip --no-cache
      - pip install docker-compose
      - apk add netcat-openbsd --no-cache
      - docker build -t cjchand/logstash-agent .
      - docker-compose down
      - docker-compose up -d
      - docker ps -a
      - sleep 30
      - curl 192.241.247.133:9200
      - nc -u 192.241.247.133 5514 << "waffles"
      - sleep 5
      - curl '192.241.247.133:9200/_all/_search?q=waffles' | grep waffles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#   publish:
#     image: cjchand/logstash-agent
#     repo: cjchand/logstash-agent
#     username: ${DOCKER_USERNAME}
#     password: ${DOCKER_PASSWORD}
