pipeline:
  build:
    image: docker
    commands:
      - apk add py-pip --no-cache
      - pip install docker-compose
      - docker build -t cjchand/logstash-agent .
      - docker-compose up -d
      - docker ps -a
      - sleep 30
      - curl drone-server:9200
      - nc -u drone-server 5514 <<< "waffles"
      - sleep 5
      - curl 'drone-server:9200/_all/_search?q=waffles' | grep waffles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#   publish:
#     image: cjchand/logstash-agent
#     repo: cjchand/logstash-agent
#     username: ${DOCKER_USERNAME}
#     password: ${DOCKER_PASSWORD}
