pipeline:
  build:
    image: docker
    commands:
      - apk add py-pip --no-cache
      - pip install docker-compose
      - docker build -t cjchand/logstash-agent .
#      - docker-compose run elasticsearch
#      - docker-compose run logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  publish:
    image: cjchand/logstash-agent
    repo: cjchand/logstash-agent
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
